{"message": "Watching for file changes with StatReloader"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\back4all\\settings.py changed, reloading."}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T12:16:46.863339Z", "level": "INFO"}
{"message": "Test!!", "timestamp": "2023-01-18T12:16:49.794086Z", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\back4all\\logging_formaters.py changed, reloading.", "timestamp": "2023-01-18T12:17:55.854309Z", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T12:18:30.630949Z", "level": "INFO"}
{"message": "Test!!", "timestamp": "2023-01-18T12:18:32.752498Z", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\back4all\\logging_formaters.py changed, reloading.", "timestamp": "2023-01-18T12:19:07.701301Z", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:19:08", "level": "INFO"}
{"message": "Test!!", "timestamp": "2023-01-18T15:19:08", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "2023-01-18T15:21:06", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:21:07", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "2023-01-18T15:22:36", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:25:39", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\back4all\\urls.py changed, reloading.", "timestamp": "2023-01-18T15:26:07", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:26:08", "level": "INFO"}
{"message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py\", line 16, in index\n    with open('sw_templates.json') as f:\nFileNotFoundError: [Errno 2] No such file or directory: 'sw_templates.json'", "status_code": 500, "request": "<WSGIRequest: GET '/'>", "timestamp": "2023-01-18T15:26:21", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:27:04", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:27:05", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:27:17", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:27:17", "level": "INFO"}
{"message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py\", line 16, in index\n    with open('../debug.log') as f:\nFileNotFoundError: [Errno 2] No such file or directory: '../debug.log'", "status_code": 500, "request": "<WSGIRequest: GET '/'>", "timestamp": "2023-01-18T15:27:23", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:27:42", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:27:43", "level": "INFO"}
{"message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py\", line 16, in index\n    with open('/debug.log') as f:\nFileNotFoundError: [Errno 2] No such file or directory: '/debug.log'", "status_code": 500, "request": "<WSGIRequest: GET '/'>", "timestamp": "2023-01-18T15:27:44", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:28:05", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:28:06", "level": "INFO"}
{"message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py\", line 17, in index\n    templates = json.load(f)\n  File \"C:\\Python39\\lib\\json\\__init__.py\", line 293, in load\n    return loads(fp.read(),\n  File \"C:\\Python39\\lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Python39\\lib\\json\\decoder.py\", line 340, in decode\n    raise JSONDecodeError(\"Extra data\", s, end)\njson.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 59)", "status_code": 500, "request": "<WSGIRequest: GET '/'>", "timestamp": "2023-01-18T15:28:06", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:29:09", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:29:09", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:29:21", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:29:22", "level": "INFO"}
{"message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py\", line 17, in index\n    templates = json.loads(json.dumps(f))\n  File \"C:\\Python39\\lib\\json\\__init__.py\", line 231, in dumps\n    return _default_encoder.encode(obj)\n  File \"C:\\Python39\\lib\\json\\encoder.py\", line 199, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"C:\\Python39\\lib\\json\\encoder.py\", line 257, in iterencode\n    return _iterencode(o, 0)\n  File \"C:\\Python39\\lib\\json\\encoder.py\", line 179, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\nTypeError: Object of type TextIOWrapper is not JSON serializable", "status_code": 500, "request": "<WSGIRequest: GET '/'>", "timestamp": "2023-01-18T15:29:26", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:30:03", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:30:03", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:30:15", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:30:16", "level": "INFO"}
{"message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py\", line 17, in index\n    templates = json.loads(f)\n  File \"C:\\Python39\\lib\\json\\__init__.py\", line 339, in loads\n    raise TypeError(f'the JSON object must be str, bytes or bytearray, '\nTypeError: the JSON object must be str, bytes or bytearray, not TextIOWrapper", "status_code": 500, "request": "<WSGIRequest: GET '/'>", "timestamp": "2023-01-18T15:30:18", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:30:59", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:31:00", "level": "INFO"}
{"message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py\", line 17, in index\n    templates = json.loads(f.read())\n  File \"C:\\Python39\\lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Python39\\lib\\json\\decoder.py\", line 340, in decode\n    raise JSONDecodeError(\"Extra data\", s, end)\njson.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 59)", "status_code": 500, "request": "<WSGIRequest: GET '/'>", "timestamp": "2023-01-18T15:31:01", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\back4all\\settings.py changed, reloading.", "timestamp": "2023-01-18T15:34:16", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:35:06", "level": "INFO"}
{"message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py\", line 17, in index\n    templates = json.loads(f.read())\n  File \"C:\\Python39\\lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Python39\\lib\\json\\decoder.py\", line 340, in decode\n    raise JSONDecodeError(\"Extra data\", s, end)\njson.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 59)", "status_code": 500, "request": "<WSGIRequest: GET '/'>", "timestamp": "2023-01-18T15:35:49", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:39:30", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:39:31", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:41:07", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:41:08", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:42:45", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:42:46", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:46:11", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:46:11", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:48:29", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:48:29", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:49:24", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:49:24", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:49:56", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:49:57", "level": "INFO"}
{"message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py\", line 21, in index\n    return render(request, 'index.html', logs=logs)\nTypeError: render() got an unexpected keyword argument 'logs'", "status_code": 500, "request": "<WSGIRequest: GET '/'>", "timestamp": "2023-01-18T15:49:57", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "2023-01-18T15:50:43", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "2023-01-18T15:50:43", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\back4all\\logging_formaters.py changed, reloading.", "timestamp": "2023-01-18T15:53:14", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 15:53:14", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\frontend\\views.py changed, reloading.", "timestamp": "18.01.2023 16:02:37", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:02:37", "level": "INFO"}
{"message": "Not Found: /get-leads/2", "status_code": 404, "request": "<WSGIRequest: GET '/get-leads/2'>", "timestamp": "18.01.2023 16:10:29", "level": "WARNING"}
{"message": "Not Found: /get-leads/2", "status_code": 404, "request": "<WSGIRequest: GET '/get-leads/2'>", "timestamp": "18.01.2023 16:10:41", "level": "WARNING"}
{"message": "Not Found: /get-leads/2", "status_code": 404, "request": "<WSGIRequest: GET '/get-leads/2'>", "timestamp": "18.01.2023 16:10:41", "level": "WARNING"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\back4all\\urls.py changed, reloading.", "timestamp": "18.01.2023 16:11:23", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:11:24", "level": "INFO"}
{"message": "Not Found: /get-leads/2", "status_code": 404, "request": "<WSGIRequest: GET '/get-leads/2'>", "timestamp": "18.01.2023 16:11:24", "level": "WARNING"}
{"message": "Not Found: /get-leads/2/", "status_code": 404, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 16:11:35", "level": "WARNING"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\urls.py changed, reloading.", "timestamp": "18.01.2023 16:12:05", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:12:06", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\urls.py changed, reloading.", "timestamp": "18.01.2023 16:12:27", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:12:28", "level": "INFO"}
{"message": "Not Found: /get-leads/2/", "status_code": 404, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 16:12:28", "level": "WARNING"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\urls.py changed, reloading.", "timestamp": "18.01.2023 16:12:51", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:12:52", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 16:12:53", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?with=contacts&page=1 HTTP/1.1\" 200 None", "timestamp": "18.01.2023 16:12:53", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 204, in _get_response\n    self.check_response(response, callback)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 332, in check_response\n    raise ValueError(\nValueError: The view amocrm.views.get_leads didn't return an HttpResponse object. It returned None instead.", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 16:12:53", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 16:13:23", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:13:24", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 16:13:24", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?with=contacts&page=1 HTTP/1.1\" 200 None", "timestamp": "18.01.2023 16:13:24", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 204, in _get_response\n    self.check_response(response, callback)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 332, in check_response\n    raise ValueError(\nValueError: The view amocrm.views.get_leads didn't return an HttpResponse object. It returned None instead.", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 16:13:24", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 16:14:03", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:14:04", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 16:18:52", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:18:53", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 16:18:55", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?with=contacts&page=1 HTTP/1.1\" 200 None", "timestamp": "18.01.2023 16:18:55", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 15, in get_leads\n    return JsonResponse(res)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\http\\response.py\", line 684, in __init__\n    raise TypeError(\nTypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 16:18:55", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 16:19:55", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:19:56", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 16:20:00", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?with=contacts&page=1 HTTP/1.1\" 200 None", "timestamp": "18.01.2023 16:20:01", "level": "DEBUG"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 16:21:11", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:21:12", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 16:25:06", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 16:25:07", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:13:35", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:13:45", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D%5B%5D=%D0%91%D0%B8%D0%BB%D0%B0%D0%B9%D0%BD HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:13:45", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 18, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:13:45", "level": "ERROR"}
{"message": "Not Found: /favicon.ico", "status_code": 404, "request": "<WSGIRequest: GET '/favicon.ico'>", "timestamp": "18.01.2023 18:13:45", "level": "WARNING"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:14:07", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:14:08", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:14:08", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D%5B%5D=%D0%91%D0%B8%D0%BB%D0%B0%D0%B9%D0%BD HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:14:09", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 19, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:14:09", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:14:44", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:14:45", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:15:43", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:15:44", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:15:49", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D%5B%5D=%D0%91%D0%B8%D0%BB%D0%B0%D0%B9%D0%BD HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:15:50", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 19, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:15:50", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:20:02", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:20:03", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:20:06", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D%5B%5D=%22%D0%91%D0%B8%D0%BB%D0%B0%D0%B9%D0%BD%22 HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:20:07", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:20:07", "level": "ERROR"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:20:29", "level": "DEBUG"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:20:29", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:20:30", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:20:30", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D=%22%D0%91%D0%B8%D0%BB%D0%B0%D0%B9%D0%BD%22 HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:20:30", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:20:31", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:21:54", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:21:55", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:21:56", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads/custom_fields HTTP/1.1\" 200 None", "timestamp": "18.01.2023 18:21:56", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: 'leads'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:21:56", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:23:51", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:23:51", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:23:53", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D=358263 HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:23:53", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:23:53", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:26:39", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:26:40", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:26:43", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D%5B%5D=358263 HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:26:43", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:26:43", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:28:17", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:28:18", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:28:18", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D%5B0%5D=358263 HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:28:18", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:28:18", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:29:39", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:29:39", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:29:40", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B%22755993%22%5D%5B%5D=%22358263%22 HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:29:40", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:29:40", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:31:46", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:31:47", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:31:51", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D%5B%5D=35263&page=1 HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:31:51", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:31:52", "level": "ERROR"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:33:03", "level": "DEBUG"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:33:03", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:33:03", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:33:04", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?page=1 HTTP/1.1\" 200 None", "timestamp": "18.01.2023 18:33:04", "level": "DEBUG"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:33:40", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:33:40", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:33:44", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:33:45", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:33:46", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads&filter%5Bstatuses%5D%5B0%5D%5Bpipeline_id%5D=6156754?page=1 HTTP/1.1\" 404 None", "timestamp": "18.01.2023 18:33:46", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:33:46", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:34:38", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:34:39", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:34:40", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads&filter%5Bstatuses%5D%5B0%5D%5Bpipeline_id%5D=6156754 HTTP/1.1\" 404 None", "timestamp": "18.01.2023 18:34:40", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:34:40", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:35:03", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:35:04", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:35:08", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bstatuses%5D%5B0%5D%5Bpipeline_id%5D=6156754 HTTP/1.1\" 200 None", "timestamp": "18.01.2023 18:35:08", "level": "DEBUG"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:35:54", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:35:54", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:36:17", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:36:18", "level": "INFO"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:36:22", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:36:23", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:36:24", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D%5B0%5D=358263 HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:36:24", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:36:24", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:36:58", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:36:58", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:36:59", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads?filter%5Bcustom_fields_values%5D%5B755993%5D%5B%5D=358263 HTTP/1.1\" 400 None", "timestamp": "18.01.2023 18:36:59", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: '_embedded'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:36:59", "level": "ERROR"}
{"message": "F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py changed, reloading.", "timestamp": "18.01.2023 18:43:36", "level": "INFO"}
{"message": "Watching for file changes with StatReloader", "timestamp": "18.01.2023 18:43:37", "level": "INFO"}
{"message": "Starting new HTTPS connection (1): alfanet.amocrm.ru:443", "timestamp": "18.01.2023 18:43:42", "level": "DEBUG"}
{"message": "https://alfanet.amocrm.ru:443 \"GET /api/v4/leads/custom_fields HTTP/1.1\" 200 None", "timestamp": "18.01.2023 18:43:42", "level": "DEBUG"}
{"message": "Internal Server Error: /get-leads/2/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"F:\\DjangoProjects\\backend4all\\venv\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\DjangoProjects\\backend4all\\back4all\\amocrm\\views.py\", line 21, in get_leads\n    res = response.json()['_embedded']['leads']\nKeyError: 'leads'", "status_code": 500, "request": "<WSGIRequest: GET '/get-leads/2/'>", "timestamp": "18.01.2023 18:43:42", "level": "ERROR"}
